# Generated by Django 4.0.5 on 2022-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0002_comment_date_comment_post_alter_blog_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='blog',
            name='comment',
            field=models.TextField(default='', max_length=1000, unique=True),
            preserve_default=False,
        ),
    ]
